name: rl4rs
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - _tflow_select=2.3.0=mkl
  - absl-py=0.15.0=pyhd3eb1b0_0
  - argon2-cffi=20.1.0=py36h27cfd23_1
  - astor=0.8.1=py36h06a4308_0
  - async_generator=1.10=py36h28b3542_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bleach=4.0.0=pyhd3eb1b0_0
  - c-ares=1.17.1=h27cfd23_0
  - ca-certificates=2021.10.26=h06a4308_2
  - certifi=2021.5.30=py36h06a4308_0
  - cffi=1.14.6=py36h400218f_0
  - coverage=5.5=py36h27cfd23_2
  - cython=0.29.24=py36h295c915_0
  - dataclasses=0.8=pyh4f3eec9_6
  - dbus=1.13.18=hb2f20db_0
  - decorator=5.1.0=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.3=py36_0
  - expat=2.4.1=h2531618_2
  - fontconfig=2.13.1=h6c09931_0
  - freetype=2.11.0=h70c0345_0
  - glib=2.69.1=h5202010_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - grpcio=1.36.1=py36h2157cd5_1
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - h5py=2.10.0=py36hd6299e0_1
  - hdf5=1.10.6=hb1b8bf9_0
  - icu=58.2=he6710b0_3
  - importlib-metadata=4.8.1=py36h06a4308_0
  - importlib_metadata=4.8.1=hd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=5.3.4=py36h5ca1d4c_0
  - ipython=7.16.1=py36h5ca1d4c_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - jedi=0.17.0=py36_0
  - jinja2=3.0.2=pyhd3eb1b0_0
  - jpeg=9d=h7f8727e_0
  - jsonschema=3.2.0=pyhd3eb1b0_2
  - jupyter=1.0.0=py36_7
  - jupyter_client=7.1.0=pyhd3eb1b0_0
  - jupyter_console=6.4.0=pyhd3eb1b0_0
  - jupyter_core=4.8.1=py36h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - keras-applications=1.0.8=py_1
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=9.3.0=h5101ec6_17
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.17.2=h4ff587b_1
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libuuid=1.0.3=h7f8727e_2
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.12=h03d6c58_0
  - markdown=3.3.4=py36h06a4308_0
  - markupsafe=2.0.1=py36h27cfd23_0
  - mistune=0.8.4=py36h7b6447c_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py36he8ac12f_0
  - mkl_fft=1.3.0=py36h54f3939_0
  - mkl_random=1.1.1=py36h0573a6f_0
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.0.7=py36_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - ncurses=6.3=h7f8727e_2
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - notebook=6.4.3=py36h06a4308_0
  - numpy=1.19.2=py36h54aff64_0
  - numpy-base=1.19.2=py36hfa32c7d_0
  - openssl=1.1.1m=h7f8727e_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandoc=2.12=h06a4308_0
  - pandocfilters=1.4.3=py36h06a4308_1
  - parso=0.8.2=pyhd3eb1b0_0
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=21.2.2=py36h06a4308_0
  - prometheus_client=0.12.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - prompt_toolkit=3.0.20=hd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.10.0=pyhd3eb1b0_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py36h05f1152_2
  - python=3.6.13=h12debd9_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pyzmq=22.2.1=py36h295c915_1
  - qt=5.9.7=h5867ecd_1
  - qtconsole=5.1.1=pyhd3eb1b0_0
  - qtpy=1.10.0=pyhd3eb1b0_0
  - readline=8.1=h27cfd23_0
  - scipy=1.3.1=py36h7c811a0_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=58.0.4=py36h06a4308_0
  - sip=4.19.8=py36hf484d3e_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.37.0=hc218d9a_0
  - termcolor=1.1.0=py36h06a4308_1
  - terminado=0.9.4=py36h06a4308_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - tk=8.6.11=h1ccaba5_0
  - tornado=6.1=py36h27cfd23_0
  - traitlets=4.3.3=py36h06a4308_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py36_1
  - werkzeug=2.0.2=pyhd3eb1b0_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - widgetsnbextension=3.5.1=py36_0
  - wrapt=1.12.1=py36h7b6447c_1
  - xz=5.2.5=h7b6447c_0
  - zeromq=4.3.4=h2531618_0
  - zipp=3.6.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7f8727e_4
  - pip:
    - aiohttp==3.7.4.post0
    - aiohttp-cors==0.7.0
    - aioredis==1.3.1
    - antlr4-python3-runtime==4.8
    - async-timeout==3.0.1
    - blessings==1.7
    - cachetools==4.2.2
    - chardet==4.0.0
    - charset-normalizer==2.0.6
    - click==8.0.1
    - cloudpickle==1.6.0
    - colorama==0.4.4
    - contextvars==2.4
    - d3rlpy==0.91
    - deepctr==0.9.0
    - dm-tree==0.1.6
    - fairseq==0.10.2
    - filelock==3.0.12
    - flask==1.1.2
    - gast==0.2.2
    - google-api-core==1.31.2
    - google-auth==1.35.0
    - googleapis-common-protos==1.53.0
    - gpustat==0.6.0
    - gputil==1.4.0
    - greenlet==1.1.2
    - gym==0.19.0
    - hiredis==2.0.0
    - hydra-core==1.1.1
    - idna==3.2
    - idna-ssl==1.1.0
    - immutables==0.16
    - importlib-resources==5.2.2
    - itsdangerous==2.0.1
    - joblib==1.0.1
    - keras==2.2.5
    - keras-embed-sim==0.10.0
    - keras-layer-normalization==0.16.0
    - keras-multi-head==0.29.0
    - keras-pos-embd==0.13.0
    - keras-position-wise-feed-forward==0.8.0
    - keras-self-attention==0.51.0
    - keras-transformer==0.40.0
    - lightseq==2.1.4
    - lz4==3.1.3
    - msgpack==1.0.2
    - multidict==5.1.0
    - ninja==1.10.2
    - nvidia-ml-py3==7.352.0
    - omegaconf==2.1.1
    - opencensus==0.7.13
    - opencensus-context==0.1.2
    - opencv-python-headless==4.3.0.36
    - opt-einsum==3.3.0
    - pandas==1.1.5
    - pandasql==0.7.3
    - portalocker==2.3.2
    - protobuf==3.19.3
    - psutil==5.8.0
    - py-spy==0.3.9
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydantic==1.8.2
    - pyrsistent==0.18.0
    - pytz==2021.1
    - pyyaml==5.4.1
    - ray==1.5.1
    - redis==3.5.3
    - regex==2021.8.28
    - requests==2.27.1
    - rsa==4.7.2
    - sacrebleu==2.0.0
    - sacremoses==0.0.45
    - scikit-learn==0.24.2
    - sklearn==0.0
    - sqlalchemy==1.4.29
    - structlog==21.3.0
    - tabulate==0.8.9
    - tensorboard==1.15.0
    - tensorboardx==2.4.1
    - tensorflow-estimator==1.15.1
    - tensorflow-gpu==1.15.0
    - threadpoolctl==2.2.0
    - torch==1.9.0
    - tqdm==4.62.2
    - urllib3==1.26.6
    - yarl==1.6.3
prefix: /project/miniconda3/envs/rl4rs